### ISSUE TITLE
Tooltip Function Breaks Custom Tooltips (CraftTweaker)

### ISSUE THREAD

**Issue by Noobulus** [jredfox/silkspawners_rewrite#3] opened 2018-05-01 03:25 UTC
When a custom tooltip is added to a spawner via CraftTweaker with SilkSpawners installed, the custom tooltip does not appear.

CraftTweaker code used for adding tooltip: `<minecraft:mob_spawner>.addTooltip(format.gray("Craft together with a filled morb to change spawner type."));`

**Comment by jredfox** [comment] 2018-05-01 05:28
show image I can't fix it if you don't show image

**Comment by jredfox** [comment] 2018-05-01 08:25
This is an issue with craft tweaker's if statement returning from the list if there is already a tooltip even if the assigned tooltip hasn't been added yet

**Closed by jredfox** 2018-05-01 08:25 UTC
Labels: feedbackRequired, unable to reproduce

**Comment by jredfox** [comment] 2018-05-01 08:31
https://github.com/CraftTweaker/CraftTweaker/issues/532

**Comment by Frontrider** [comment] 2018-05-01 17:26
It looks like that any tooltip created with the help of CohfCore works fine (Thermal Expansion has some really expensive tooltips), so the issue is probably on your side.

**Comment by Frontrider** [comment] 2018-05-01 17:28
Your code is probably correct, but there might be some sort of minor overlook or something.

**Comment by Noobulus** [comment] 2018-05-01 20:57
I've tested it with items that already had tooltips (i.e. TE machines) and it works fine with those. The instance that I originally tested the tooltip bug can be found [here.](https://drive.google.com/file/d/1kz98VRd4KKdbN7hAZx7VzCN2J1IHBqaH/view?usp=sharing)

I've also tried it with `<minecraft:mob_spawner>.clearTooltip();` before tooltip was added and nothing changed.

**Comment by jredfox** [comment] 2018-05-01 21:31
Well I add mine via events but, I don't remove anything still not my issue on why it's not showing up

**Comment by jredfox** [comment] 2018-05-02 00:01
@Frontrider look at my tooltip event I don't remove anything. It's not on my side I only added the tooltips. If it was on my side It would have either been fixed in 2 seconds or been purposeful that I was clearing the list.
